name: 🐞 Bug report
description: Create a report to help us reproduce and fix the bug
title: "[Bug] "
labels: ['Bug']

body:
- type: textarea
  attributes:
    label: Environment
    description: |
      Please share your environment with us. You can run the command **python fastvideo/utils/env_utils.py** and copy-paste its output below.
    placeholder: FastVideo version, platform, python version, cuda version...
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: |
      What command or script did you run? Which **model** are you using?
    placeholder: |
      A placeholder for the command.
  validations:
    required: true