torchrun --nnodes 4 --nproc_per_node 4 \
    --node_rank=3 \
    --rdzv_id=456 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=172.23.30.15:29500 \
    fastvideo/train.py \
    --seed 42 \
    --pretrained_model_name_or_path data/mochi \
    --cache_dir "data/.cache" \
    --data_json_path "data/BLACK-MYTH-Finetune-Dataset/videos2caption.json" \
    --validation_prompt_dir "data/BLACK-MYTH-Finetune-Dataset/validation_prompt_embed_mask" \
    --uncond_prompt_dir "data/BLACK-MYTH-Finetune-Dataset/uncond_prompt_embed_mask" \
    --gradient_checkpointing \
    --train_batch_size=1 \
    --num_latent_t 16 \
    --sp_size 4 \
    --train_sp_batch_size 4 \
    --dataloader_num_workers 4 \
    --gradient_accumulation_steps=1 \
    --max_train_steps=4000 \
    --learning_rate=2e-5 \
    --mixed_precision="bf16" \
    --checkpointing_steps=500 \
    --validation_steps=100 \
    --validation_sampling_steps 64 \
    --checkpoints_total_limit 3 \
    --allow_tf32 \
    --ema_start_step 0 \
    --cfg 0.0 \
    --ema_decay 0.999 \
    --log_validation \
    --output_dir="data/outputs/black_myth_correct_video_mask" \
    --weighting_scheme "uniform" \
    --num_frames 91 \
    --selective_checkpointing 1.0

